import type { FarmerUser } from '../types/admin';

export const mockFarmers: FarmerUser[] = [
  {
    id: 'frm-101',
    farmerCode: '#FMR-8921',
    fullName: 'Ramesh Patel',
    phone: '+91 98230 41122',
    mandiName: 'Nashik Main Mandi',
    district: 'Nashik',
    state: 'Maharashtra',
    landAreaAcres: 4.5,
    verificationStatus: 'VERIFIED',
    rating: 4.9,
    totalSalesAmount: 485000,
    joinedDate: '12 Jan 2024',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-9012', verifiedStatus: 'VERIFIED', uploadedAt: '12 Jan 2024', verifiedAt: '13 Jan 2024' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-402/2023', verifiedStatus: 'VERIFIED', uploadedAt: '12 Jan 2024', verifiedAt: '14 Jan 2024' },
      { documentType: 'BANK_PASSBOOK', documentNumber: 'SBIN0004921', verifiedStatus: 'VERIFIED', uploadedAt: '12 Jan 2024', verifiedAt: '14 Jan 2024' },
    ],
    activeListings: [
      { id: 'lst-1', cropName: 'Tomatoes (Hybrid)', category: 'Vegetables', availableKg: 2500, pricePerKg: 35, qualityGrade: 'GRADE_A', harvestDate: '02 Sep 2026', status: 'ACTIVE' },
      { id: 'lst-2', cropName: 'Red Onion (Nashik)', category: 'Vegetables', availableKg: 5000, pricePerKg: 28, qualityGrade: 'PREMIUM', harvestDate: '28 Aug 2026', status: 'ACTIVE' },
      { id: 'lst-101', farmerId: 'frm-101', farmerName: 'Ramesh Patel', farmerCode: '#FMR-8921', cropName: 'Green Capsicum (Bell Pepper)', category: 'Vegetables', availableKg: 1800, pricePerKg: 52, qualityGrade: 'PREMIUM', harvestDate: '04 Sep 2026', status: 'PENDING_APPROVAL', mandiName: 'Nashik Main Mandi', submittedAt: 'Today, 11:30 AM', labCertificateNumber: 'LAB-NSK-9902' },
    ],
  },
  {
    id: 'frm-102',
    farmerCode: '#FMR-8922',
    fullName: 'Gurpreet Singh',
    phone: '+91 94172 88390',
    mandiName: 'Ludhiana Grain Market',
    district: 'Ludhiana',
    state: 'Punjab',
    landAreaAcres: 8.0,
    verificationStatus: 'VERIFIED',
    rating: 4.8,
    totalSalesAmount: 920000,
    joinedDate: '05 Feb 2024',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-4411', verifiedStatus: 'VERIFIED', uploadedAt: '05 Feb 2024' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-109/2022', verifiedStatus: 'VERIFIED', uploadedAt: '05 Feb 2024' },
    ],
    activeListings: [
      { id: 'lst-3', cropName: 'Wheat (Sharbati Gold)', category: 'Grains', availableKg: 12000, pricePerKg: 33, qualityGrade: 'PREMIUM', harvestDate: '15 Aug 2026', status: 'ACTIVE' },
      { id: 'lst-102', farmerId: 'frm-102', farmerName: 'Gurpreet Singh', farmerCode: '#FMR-8922', cropName: 'Organic Basmati Rice 1121', category: 'Grains', availableKg: 4500, pricePerKg: 85, qualityGrade: 'PREMIUM', harvestDate: '03 Sep 2026', status: 'PENDING_APPROVAL', mandiName: 'Ludhiana Grain Market', submittedAt: 'Today, 09:15 AM', labCertificateNumber: 'LAB-LDH-4410' },
    ],
  },
  {
    id: 'frm-103',
    farmerCode: '#FMR-8923',
    fullName: 'Anita Devi',
    phone: '+91 97120 33491',
    mandiName: 'Patna Central Mandi',
    district: 'Patna',
    state: 'Bihar',
    landAreaAcres: 2.8,
    verificationStatus: 'PENDING_KYC',
    rating: 4.6,
    totalSalesAmount: 142000,
    joinedDate: '28 Aug 2026',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-7720', verifiedStatus: 'VERIFIED', uploadedAt: '28 Aug 2026' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-882/2026', verifiedStatus: 'PENDING', uploadedAt: '29 Aug 2026' },
    ],
    activeListings: [
      { id: 'lst-4', cropName: 'Potato (Jyoti Fresh)', category: 'Vegetables', availableKg: 3000, pricePerKg: 26, qualityGrade: 'GRADE_A', harvestDate: '01 Sep 2026', status: 'ACTIVE' },
    ],
  },
  {
    id: 'frm-104',
    farmerCode: '#FMR-8924',
    fullName: 'Suresh Kumar',
    phone: '+91 98901 22910',
    mandiName: 'Nagpur Fruit Mandi',
    district: 'Nagpur',
    state: 'Maharashtra',
    landAreaAcres: 6.2,
    verificationStatus: 'SUSPENDED',
    rating: 3.9,
    totalSalesAmount: 310000,
    joinedDate: '10 Nov 2024',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-1100', verifiedStatus: 'VERIFIED', uploadedAt: '10 Nov 2024' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-551/2024', verifiedStatus: 'REJECTED', uploadedAt: '12 Nov 2024' },
    ],
    activeListings: [],
  },
  {
    id: 'frm-105',
    farmerCode: '#FMR-8925',
    fullName: 'Vikram Jadhav',
    phone: '+91 91580 99421',
    mandiName: 'Pune Agriculture Market',
    district: 'Pune',
    state: 'Maharashtra',
    landAreaAcres: 5.0,
    verificationStatus: 'VERIFIED',
    rating: 4.9,
    totalSalesAmount: 640000,
    joinedDate: '19 Mar 2024',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-3349', verifiedStatus: 'VERIFIED', uploadedAt: '19 Mar 2024' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-701/2024', verifiedStatus: 'VERIFIED', uploadedAt: '20 Mar 2024' },
    ],
    activeListings: [
      { id: 'lst-5', cropName: 'Pomegranate (Bhagwa)', category: 'Fruits', availableKg: 1500, pricePerKg: 120, qualityGrade: 'PREMIUM', harvestDate: '30 Aug 2026', status: 'ACTIVE' },
    ],
  },
];
