import type { FarmerUser } from '../types/admin';

/*
// DEMO/MOCK FARMERS DATA (COMMENTED OUT FOR RETRIEVAL)
export const DEMO_MOCK_FARMERS: FarmerUser[] = [
  {
    id: 'frm-101',
    farmerCode: '#FMR-8921',
    fullName: 'Ramesh Patel',
    phone: '+91 98230 41122',
    mandiName: 'Nashik Main Mandi',
    district: 'Nashik',
    state: 'Maharashtra',
    landAreaAcres: 8.5,
    verificationStatus: 'VERIFIED',
    rating: 4.9,
    totalSalesAmount: 385000,
    joinedDate: '12 Jan 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-9012', verifiedStatus: 'VERIFIED', uploadedAt: '12 Jan 2024', verifiedAt: '13 Jan 2024' },
      { documentType: 'KHASRA_LAND_RECORD', documentNumber: 'KH-402/2023', verifiedStatus: 'VERIFIED', uploadedAt: '12 Jan 2024', verifiedAt: '13 Jan 2024' },
    ],
    activeListings: [
      {
        id: 'lst-1',
        cropName: 'Tomatoes (Hybrid Grade A)',
        category: 'Vegetables',
        availableKg: 1500,
        pricePerKg: 32,
        qualityGrade: 'GRADE_A',
        harvestDate: '02 Sep 2026',
        status: 'ACTIVE',
        mandiName: 'Nashik Main Mandi',
        submittedAt: '03 Sep 2026',
        imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
      },
      {
        id: 'lst-2',
        cropName: 'Red Onion (Nashik Export)',
        category: 'Vegetables',
        availableKg: 2500,
        pricePerKg: 28,
        qualityGrade: 'PREMIUM',
        harvestDate: '01 Sep 2026',
        status: 'PENDING_APPROVAL',
        mandiName: 'Nashik Main Mandi',
        submittedAt: '05 Sep 2026',
        imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'frm-102',
    farmerCode: '#FMR-5412',
    fullName: 'Suresh Patil',
    phone: '+91 94220 88990',
    mandiName: 'Nagpur Cotton & Orange Mandi',
    district: 'Nagpur',
    state: 'Maharashtra',
    landAreaAcres: 12.0,
    verificationStatus: 'VERIFIED',
    rating: 4.8,
    totalSalesAmount: 520000,
    joinedDate: '20 Feb 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-4421', verifiedStatus: 'VERIFIED', uploadedAt: '20 Feb 2024', verifiedAt: '21 Feb 2024' },
    ],
    activeListings: [
      {
        id: 'lst-3',
        cropName: 'Nagpur Oranges (Sweet Mandarin)',
        category: 'Fruits',
        availableKg: 3000,
        pricePerKg: 45,
        qualityGrade: 'GRADE_A',
        harvestDate: '30 Aug 2026',
        status: 'PENDING_APPROVAL',
        mandiName: 'Nagpur APMC',
        submittedAt: '04 Sep 2026',
        imageUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=500&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'frm-103',
    farmerCode: '#FMR-3190',
    fullName: 'Baldev Singh',
    phone: '+91 97180 12345',
    mandiName: 'Karnal Grain Market',
    district: 'Karnal',
    state: 'Haryana',
    landAreaAcres: 18.0,
    verificationStatus: 'VERIFIED',
    rating: 5.0,
    totalSalesAmount: 780000,
    joinedDate: '15 Mar 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    kycRecords: [
      { documentType: 'AADHAAR', documentNumber: 'XXXX-XXXX-8910', verifiedStatus: 'VERIFIED', uploadedAt: '15 Mar 2024', verifiedAt: '16 Mar 2024' },
    ],
    activeListings: [
      {
        id: 'lst-4',
        cropName: 'Golden Sharbati Wheat',
        category: 'Grains',
        availableKg: 5000,
        pricePerKg: 30,
        qualityGrade: 'PREMIUM',
        harvestDate: '28 Aug 2026',
        status: 'ACTIVE',
        mandiName: 'Karnal APMC',
        submittedAt: '02 Sep 2026',
        imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&auto=format&fit=crop&q=80',
      },
    ],
  },
];
*/

export const mockFarmers: FarmerUser[] = [];

