import type { 
  LogisticsShipment, 
  CarrierPartner, 
  PriceForecast, 
  SpoilageRiskAlert, 
  SupplyDemandForecast 
} from '../types/logisticsAndAi';

export const MOCK_SHIPMENTS: LogisticsShipment[] = [
  {
    id: 'shp-001',
    trackingId: 'TRK-9402-MH',
    orderId: 'ORD-9402',
    carrierName: 'AgroTruck Express',
    driverName: 'Santosh Pawar',
    driverPhone: '+91 98221 00991',
    vehicleNumber: 'MH-15-EG-4902',
    produceName: 'Tomatoes (Hybrid Grade A)',
    quantityKg: 2500,
    originMandi: 'Nashik Central Mandi',
    destinationHub: 'Cold Storage Hub #4, Thane, Mumbai',
    departureTime: '2026-09-04 06:30 AM',
    estimatedArrival: 'Today, 06:00 PM',
    status: 'IN_TRANSIT',
    isReefer: true,
    targetTempCelsius: 4.0,
    currentTempCelsius: 4.5,
    batteryLevelPct: 88,
    gpsCoordinates: { lat: 19.9975, lng: 73.7898 },
  },
  {
    id: 'shp-002',
    trackingId: 'TRK-9399-MH',
    orderId: 'ORD-9399',
    carrierName: 'Reefer Express Cold Chain',
    driverName: 'Vikram Shinde',
    driverPhone: '+91 97640 12345',
    vehicleNumber: 'MH-31-CB-8812',
    produceName: 'Oranges (Nagpur Grade 1)',
    quantityKg: 800,
    originMandi: 'Nagpur Fruit Market',
    destinationHub: 'JNPT Port Container Terminal, Navi Mumbai',
    departureTime: '2026-09-03 01:30 PM',
    estimatedArrival: 'Delayed (Temp Alert)',
    status: 'TEMP_ALERT',
    isReefer: true,
    targetTempCelsius: 18.0,
    currentTempCelsius: 26.2,
    batteryLevelPct: 34,
    gpsCoordinates: { lat: 20.7002, lng: 77.0082 },
  },
  {
    id: 'shp-003',
    trackingId: 'TRK-9401-PB',
    orderId: 'ORD-9401',
    carrierName: 'Punjab Cargo Freight',
    driverName: 'Harpreet Singh',
    driverPhone: '+91 98140 55443',
    vehicleNumber: 'PB-10-DF-1122',
    produceName: 'Wheat (Sharbati Gold)',
    quantityKg: 5000,
    originMandi: 'Ludhiana Grain Market',
    destinationHub: 'FCI Storage Yard, Jalandhar',
    departureTime: '2026-09-04 09:30 AM',
    estimatedArrival: 'Tomorrow, 10:00 AM',
    status: 'LOADING',
    isReefer: false,
    targetTempCelsius: 25.0,
    currentTempCelsius: 25.4,
    batteryLevelPct: 95,
    gpsCoordinates: { lat: 30.9010, lng: 75.8573 },
  },
  {
    id: 'shp-004',
    trackingId: 'TRK-9400-BR',
    orderId: 'ORD-9400',
    carrierName: 'Local Mandi Logistics',
    driverName: 'Manoj Kumar',
    driverPhone: '+91 94312 88776',
    vehicleNumber: 'BR-01-GA-3321',
    produceName: 'Potato (Jyoti Fresh)',
    quantityKg: 1200,
    originMandi: 'Patna Sabzi Mandi',
    destinationHub: 'Store #12, Kankerbagh, Patna',
    departureTime: '2026-09-03 04:30 PM',
    estimatedArrival: 'Delivered',
    status: 'DELIVERED',
    isReefer: false,
    targetTempCelsius: 22.0,
    currentTempCelsius: 22.1,
    batteryLevelPct: 100,
    gpsCoordinates: { lat: 25.5941, lng: 85.1376 },
  },
];

export const MOCK_CARRIERS: CarrierPartner[] = [
  {
    id: 'car-101',
    name: 'AgroTruck Express',
    code: 'ATE-MH',
    activeFleetSize: 45,
    onTimeDeliveryPct: 96.8,
    totalDeliveries: 1420,
    rating: 4.9,
    contactPerson: 'Sunil Deshmukh',
    contactPhone: '+91 98220 11223',
  },
  {
    id: 'car-102',
    name: 'Reefer Express Cold Chain',
    code: 'REC-MH',
    activeFleetSize: 28,
    onTimeDeliveryPct: 89.2,
    totalDeliveries: 890,
    rating: 4.3,
    contactPerson: 'Anil Kadam',
    contactPhone: '+91 98221 44556',
  },
  {
    id: 'car-103',
    name: 'Punjab Cargo Freight',
    code: 'PCF-PB',
    activeFleetSize: 60,
    onTimeDeliveryPct: 94.5,
    totalDeliveries: 2310,
    rating: 4.8,
    contactPerson: 'Jaswinder Dhillon',
    contactPhone: '+91 98141 77889',
  },
];

export const MOCK_PRICE_FORECASTS: PriceForecast[] = [
  {
    cropName: 'Tomatoes (Hybrid Grade A)',
    category: 'Vegetables',
    currentAvgPricePerKg: 35.0,
    predicted7DayPricePerKg: 42.5,
    predictedChangePct: +21.4,
    confidencePct: 94.8,
    trend: 'UPWARD',
    primaryFactor: 'Unseasonal monsoon rainfall in Nashik & Pune growing clusters disrupting harvest.',
    recommendedBasePrice: 40.0,
  },
  {
    cropName: 'Onions (Nashik Red Grade 1)',
    category: 'Vegetables',
    currentAvgPricePerKg: 25.0,
    predicted7DayPricePerKg: 22.0,
    predictedChangePct: -12.0,
    confidencePct: 91.2,
    trend: 'DOWNWARD',
    primaryFactor: 'Fresh rabi crop arrivals surging in Lasalgaon mandi by +35% volume.',
    recommendedBasePrice: 23.0,
  },
  {
    cropName: 'Wheat (Sharbati Gold)',
    category: 'Grains',
    currentAvgPricePerKg: 33.0,
    predicted7DayPricePerKg: 33.8,
    predictedChangePct: +2.4,
    confidencePct: 96.5,
    trend: 'STABLE',
    primaryFactor: 'Steady procurement by retail chains matching seasonal buffer stocks.',
    recommendedBasePrice: 33.5,
  },
  {
    cropName: 'Potatoes (Jyoti Grade A)',
    category: 'Vegetables',
    currentAvgPricePerKg: 26.0,
    predicted7DayPricePerKg: 29.2,
    predictedChangePct: +12.3,
    confidencePct: 89.5,
    trend: 'UPWARD',
    primaryFactor: 'Increased cold-storage hoarding ahead of festive demand spike.',
    recommendedBasePrice: 28.0,
  },
];

export const MOCK_SPOILAGE_ALERTS: SpoilageRiskAlert[] = [
  {
    id: 'spl-301',
    batchId: 'BATCH-NAG-9399',
    cropName: 'Oranges (Nagpur Grade 1)',
    farmerName: 'Suresh Kumar',
    quantityKg: 800,
    transitHoursElapsed: 26,
    estimatedRemainingShelfHours: 8,
    riskSeverity: 'CRITICAL',
    currentTempCelsius: 26.2,
    recommendedAction: 'Reroute to nearest juice processing plant in Akola within 4 hours to recover 70% value.',
    location: 'En route near Akola Bypass (NH-6)',
  },
  {
    id: 'spl-302',
    batchId: 'BATCH-NSK-4902',
    cropName: 'Tomatoes (Hybrid Grade A)',
    farmerName: 'Ramesh Patel',
    quantityKg: 2500,
    transitHoursElapsed: 10,
    estimatedRemainingShelfHours: 36,
    riskSeverity: 'MODERATE',
    currentTempCelsius: 4.5,
    recommendedAction: 'Refrigeration stable; maintain speed limit for 06:00 PM delivery.',
    location: 'Igatpuri Expressway Ghat Section',
  },
];

export const MOCK_SUPPLY_DEMAND: SupplyDemandForecast[] = [
  {
    region: 'Western Maharashtra',
    state: 'Maharashtra',
    cropName: 'Tomatoes',
    expectedHarvestTons: 1450,
    buyerDemandTons: 1900,
    balanceState: 'DEFICIT',
    gapTons: -450,
  },
  {
    region: 'Malwa Belt',
    state: 'Madhya Pradesh',
    cropName: 'Soybean',
    expectedHarvestTons: 3200,
    buyerDemandTons: 2400,
    balanceState: 'SURPLUS',
    gapTons: +800,
  },
  {
    region: 'Doab Region',
    state: 'Punjab & Haryana',
    cropName: 'Wheat',
    expectedHarvestTons: 8500,
    buyerDemandTons: 8400,
    balanceState: 'BALANCED',
    gapTons: +100,
  },
];
