import type { DetailedOrder, DisputeCase } from '../types/ordersAndDisputes';

export const mockDetailedOrders: DetailedOrder[] = [
  {
    id: 'ORD-9401',
    orderNumber: '#MK-9401',
    farmerName: 'Ramesh Patel',
    farmerCode: 'FMR-8921',
    farmerPhone: '+91 98230 41122',
    farmerLocation: 'Nashik, Maharashtra',
    buyerName: 'Vikram Mehta',
    buyerCompany: 'BigBasket Wholesale Hub',
    buyerPhone: '+91 91234 56789',
    buyerLocation: 'Thane, Mumbai',
    produceName: 'Tomatoes (Hybrid Grade A)',
    cropName: 'Tomatoes (Hybrid Grade A)',
    qualityGrade: 'Grade A',
    quantityKg: 1500,
    pricePerKg: 32,
    totalAmount: 48000,
    totalPrice: 48000,
    status: 'PLACED',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Nashik Main Mandi',
    district: 'Nashik',
    createdAt: '2026-09-05 11:30 AM',
    timestamp: '2026-09-05 11:30 AM',
    deliveryAddress: 'Cold Storage Hub #4, Thane West, Mumbai',
    logisticsPartner: 'AgroTruck Logistics',
    logisticsTrackingId: 'TRK-9401-MH',
    estimatedDelivery: 'Tomorrow, 10:00 AM',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ORD-9402',
    orderNumber: '#MK-9402',
    farmerName: 'Ramesh Patel',
    farmerCode: 'FMR-8921',
    farmerPhone: '+91 98230 41122',
    farmerLocation: 'Nashik, Maharashtra',
    buyerName: 'Pooja Deshmukh',
    buyerCompany: 'FreshPicks Supermarket',
    buyerPhone: '+91 98221 34567',
    buyerLocation: 'Pune, Maharashtra',
    produceName: 'Red Onion (Nashik Export)',
    cropName: 'Red Onion (Nashik Export)',
    qualityGrade: 'Grade A',
    quantityKg: 2000,
    pricePerKg: 28,
    totalAmount: 56000,
    totalPrice: 56000,
    status: 'IN_TRANSIT',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Nashik Central Mandi',
    district: 'Nashik',
    createdAt: '2026-09-04 10:15 AM',
    timestamp: '2026-09-04 10:15 AM',
    deliveryAddress: 'FreshPicks Central Depot, Hadapsar, Pune',
    logisticsPartner: 'ReeferExpress Fleet',
    logisticsTrackingId: 'TRK-9402-MH',
    estimatedDelivery: 'Today, 06:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ORD-9403',
    orderNumber: '#MK-9403',
    farmerName: 'Suresh Patil',
    farmerCode: 'FMR-5412',
    farmerPhone: '+91 94220 88990',
    farmerLocation: 'Nagpur, Maharashtra',
    buyerName: 'Sunil Verma',
    buyerCompany: 'Citrus Juice Exports',
    buyerPhone: '+91 98111 22334',
    buyerLocation: 'JNPT Port, Navi Mumbai',
    produceName: 'Nagpur Oranges (Sweet Mandarin)',
    cropName: 'Nagpur Oranges (Sweet Mandarin)',
    qualityGrade: 'Grade A',
    quantityKg: 3000,
    pricePerKg: 45,
    totalAmount: 135000,
    totalPrice: 135000,
    status: 'COMPLETED',
    escrowStatus: 'RELEASED_TO_FARMER',
    mandiName: 'Nagpur Cotton & Orange Mandi',
    district: 'Nagpur',
    createdAt: '2026-09-03 02:40 PM',
    timestamp: '2026-09-03 02:40 PM',
    deliveryAddress: 'Cold Berth Terminal #2, JNPT, Navi Mumbai',
    logisticsPartner: 'AgroTruck Express',
    logisticsTrackingId: 'TRK-9403-MH',
    estimatedDelivery: 'Delivered',
    imageUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ORD-9404',
    orderNumber: '#MK-9404',
    farmerName: 'Baldev Singh',
    farmerCode: 'FMR-3190',
    farmerPhone: '+91 97180 12345',
    farmerLocation: 'Karnal, Haryana',
    buyerName: 'Rajinder Kumar',
    buyerCompany: 'Punjab Mills & Grocers',
    buyerPhone: '+91 98770 99887',
    buyerLocation: 'Delhi Azadpur APMC',
    produceName: 'Golden Sharbati Wheat',
    cropName: 'Golden Sharbati Wheat',
    qualityGrade: 'Premium',
    quantityKg: 4000,
    pricePerKg: 30,
    totalAmount: 120000,
    totalPrice: 120000,
    status: 'PLACED',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Karnal Grain Market',
    district: 'Karnal',
    createdAt: '2026-09-05 09:20 AM',
    timestamp: '2026-09-05 09:20 AM',
    deliveryAddress: 'Shed #14, Azadpur Mandi, Delhi',
    logisticsPartner: 'NorthLogistics Corp',
    logisticsTrackingId: 'TRK-9404-DL',
    estimatedDelivery: 'Tomorrow, 04:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ORD-9405',
    orderNumber: '#MK-9405',
    farmerName: 'Harish Chandra',
    farmerCode: 'FMR-7201',
    farmerPhone: '+91 96540 11223',
    farmerLocation: 'Agra, Uttar Pradesh',
    buyerName: 'Kishore Snacks Ltd',
    buyerCompany: 'Kishore Snacks Ltd',
    buyerPhone: '+91 98100 44556',
    buyerLocation: 'Noida, Uttar Pradesh',
    produceName: 'Kufri Jyoti Potatoes',
    cropName: 'Kufri Jyoti Potatoes',
    qualityGrade: 'Grade A',
    quantityKg: 5000,
    pricePerKg: 22,
    totalAmount: 110000,
    totalPrice: 110000,
    status: 'CONFIRMED',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Agra Potato Mandi',
    district: 'Agra',
    createdAt: '2026-09-04 04:10 PM',
    timestamp: '2026-09-04 04:10 PM',
    deliveryAddress: 'Sector 62 Food Processing Park, Noida',
    logisticsPartner: 'AgroTruck Express',
    logisticsTrackingId: 'TRK-9405-UP',
    estimatedDelivery: 'Today, 09:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80',
  }
];

export const mockDisputeCases: DisputeCase[] = [
  {
    id: 'DSP-201',
    disputeNumber: '#DSP-104',
    orderId: 'ORD-9402',
    orderNumber: '#MK-9402',
    farmerName: 'Suresh Kumar',
    buyerName: 'AgroExport Co-Op',
    produceName: 'Oranges (Nagpur Grade 1)',
    cropName: 'Oranges (Nagpur Grade 1)',
    disputingParty: 'buyer',
    disputeReason: 'COLD_CHAIN_SPOILAGE',
    disputedAmount: 45000,
    amountDisputed: 45000,
    category: 'SPOILAGE',
    severity: 'CRITICAL',
    status: 'OPEN',
    openedAt: '2026-09-03 03:45 PM',
    farmerClaim: 'Produce was loaded in pristine condition at 18°C. Temperature spike occurred due to logistics reefer failure.',
    buyerClaim: 'Container arrived at JNPT with internal temp of 26°C. High moisture damage.',
    description: 'Buyer claims produce arrived spoiled due to reefer truck refrigeration unit failure during transit.',
    evidencePhotoUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=500&auto=format&fit=crop&q=80',
    weightSlipNumber: 'WS-NAG-49021',
    expectedGrade: 'Export Grade A',
    receivedGrade: 'Grade C (Softened/Spoiled)',
    evidenceFiles: ['Inspection_Report.pdf'],
  },
  {
    id: 'DSP-202',
    disputeNumber: '#DSP-105',
    orderId: 'ORD-9401',
    orderNumber: '#MK-9401',
    farmerName: 'Ramesh Patel',
    buyerName: 'Vikram Mehta',
    produceName: 'Tomatoes (Hybrid Grade A)',
    cropName: 'Tomatoes (Hybrid Grade A)',
    disputingParty: 'buyer',
    disputeReason: 'WEIGHT_MISMATCH',
    disputedAmount: 4800,
    amountDisputed: 4800,
    category: 'WEIGHT_MISMATCH',
    severity: 'MINOR',
    status: 'UNDER_REVIEW',
    openedAt: '2026-09-04 05:15 PM',
    farmerClaim: 'Loaded weight was exactly 1500 kg as calibrated on Nashik APMC weighbridge.',
    buyerClaim: 'Weigh-in at Thane cold hub logged 1350 kg (150 kg difference due to in-transit dehydration/leakage).',
    description: 'Quantity shortage dispute of 150 kg on arrival at Thane hub.',
    evidencePhotoUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
    weightSlipNumber: 'WS-NSK-10928',
    expectedGrade: 'Grade A',
    receivedGrade: 'Grade A',
    evidenceFiles: ['Weighbridge_Slip_Thane.pdf'],
  }
];

export const MOCK_ORDERS = mockDetailedOrders;
export const MOCK_DISPUTES = mockDisputeCases;
