import type { DetailedOrder, DisputeCase } from '../types/ordersAndDisputes';

export const mockDetailedOrders: DetailedOrder[] = [
  {
    id: 'ORD-9402',
    orderNumber: '#MK-9402',
    farmerName: 'Ramesh Patel',
    farmerCode: 'FMR-8921',
    farmerPhone: '+91 98765 43210',
    farmerLocation: 'Nashik, Maharashtra',
    buyerName: 'Vikram Mehta',
    buyerCompany: 'BigBasket Bulk Ops',
    buyerPhone: '+91 91234 56789',
    buyerLocation: 'Thane, Mumbai',
    produceName: 'Tomatoes (Hybrid Grade A)',
    cropName: 'Tomatoes (Hybrid Grade A)',
    qualityGrade: 'Grade A',
    quantityKg: 2500,
    pricePerKg: 35,
    totalAmount: 87500,
    totalPrice: 87500,
    status: 'IN_TRANSIT',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Nashik Central Mandi',
    district: 'Nashik',
    createdAt: '2026-09-04 10:15 AM',
    timestamp: '2026-09-04 10:15 AM',
    deliveryAddress: 'Cold Storage Hub #4, Thane West, Mumbai',
    logisticsPartner: 'AgroTruck Express',
    logisticsTrackingId: 'TRK-9402-MH',
    estimatedDelivery: 'Today, 06:00 PM',
  },
  {
    id: 'ORD-9401',
    orderNumber: '#MK-9401',
    farmerName: 'Gurpreet Singh',
    farmerCode: 'FMR-4102',
    farmerPhone: '+91 98111 22233',
    farmerLocation: 'Ludhiana, Punjab',
    buyerName: 'Harvinder Gill',
    buyerCompany: 'Punjab Organic Retails',
    buyerPhone: '+91 98777 66554',
    buyerLocation: 'Jalandhar, Punjab',
    produceName: 'Wheat (Sharbati Gold)',
    cropName: 'Wheat (Sharbati Gold)',
    qualityGrade: 'Premium Gold',
    quantityKg: 5000,
    pricePerKg: 33,
    totalAmount: 165000,
    totalPrice: 165000,
    status: 'CONFIRMED',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Ludhiana Grain Market',
    district: 'Ludhiana',
    createdAt: '2026-09-04 09:30 AM',
    timestamp: '2026-09-04 09:30 AM',
    deliveryAddress: 'FCI Approved Storage Yard, Jalandhar',
    logisticsPartner: 'Punjab Cargo Freight',
    logisticsTrackingId: 'TRK-9401-PB',
    estimatedDelivery: 'Tomorrow, 10:00 AM',
  },
  {
    id: 'ORD-9400',
    orderNumber: '#MK-9400',
    farmerName: 'Anita Devi',
    farmerCode: 'FMR-3390',
    farmerPhone: '+91 94310 99887',
    farmerLocation: 'Patna, Bihar',
    buyerName: 'Sanjay Gupta',
    buyerCompany: 'FreshCart Direct Consumer',
    buyerPhone: '+91 99340 11223',
    buyerLocation: 'Patna, Bihar',
    produceName: 'Potato (Jyoti Fresh)',
    cropName: 'Potato (Jyoti Fresh)',
    qualityGrade: 'Grade A',
    quantityKg: 1200,
    pricePerKg: 26,
    totalAmount: 31200,
    totalPrice: 31200,
    status: 'COMPLETED',
    escrowStatus: 'RELEASED_TO_FARMER',
    mandiName: 'Patna Sabzi Mandi',
    district: 'Patna',
    createdAt: '2026-09-03 04:20 PM',
    timestamp: '2026-09-03 04:20 PM',
    deliveryAddress: 'Store #12, Kankerbagh, Patna',
    logisticsPartner: 'Local Mandi Logistics',
    logisticsTrackingId: 'TRK-9400-BR',
    estimatedDelivery: 'Delivered (Sept 03)',
  },
  {
    id: 'ORD-9399',
    orderNumber: '#MK-9399',
    farmerName: 'Suresh Kumar',
    farmerCode: 'FMR-5521',
    farmerPhone: '+91 97654 32109',
    farmerLocation: 'Nagpur, Maharashtra',
    buyerName: 'Alok Sharma',
    buyerCompany: 'AgroExport Co-Op',
    buyerPhone: '+91 98220 54321',
    buyerLocation: 'Navi Mumbai, Maharashtra',
    produceName: 'Oranges (Nagpur Grade 1)',
    cropName: 'Oranges (Nagpur Grade 1)',
    qualityGrade: 'Export Grade',
    quantityKg: 800,
    pricePerKg: 70,
    totalAmount: 56000,
    totalPrice: 56000,
    status: 'DISPUTED',
    escrowStatus: 'HELD_IN_ESCROW',
    mandiName: 'Nagpur Cotton & Fruit Market',
    district: 'Nagpur',
    createdAt: '2026-09-03 01:10 PM',
    timestamp: '2026-09-03 01:10 PM',
    deliveryAddress: 'JNPT Port Container Terminal, Navi Mumbai',
    logisticsPartner: 'Reefer Express Cold Chain',
    logisticsTrackingId: 'TRK-9399-MH',
    estimatedDelivery: 'In Dispute Review',
  },
  {
    id: 'ORD-9398',
    orderNumber: '#MK-9398',
    farmerName: 'Vikram Jadhav',
    farmerCode: 'FMR-9012',
    farmerPhone: '+91 99700 88776',
    farmerLocation: 'Pune, Maharashtra',
    buyerName: 'Chef Rahul',
    buyerCompany: 'Hotel Taj Procurement',
    buyerPhone: '+91 98200 11111',
    buyerLocation: 'Colaba, Mumbai',
    produceName: 'Onion (Red Nashik)',
    cropName: 'Onion (Red Nashik)',
    qualityGrade: 'Grade A',
    quantityKg: 3000,
    pricePerKg: 25,
    totalAmount: 75000,
    totalPrice: 75000,
    status: 'DELIVERED',
    escrowStatus: 'RELEASED_TO_FARMER',
    mandiName: 'Pune Agricultural Market',
    district: 'Pune',
    createdAt: '2026-09-02 11:00 AM',
    timestamp: '2026-09-02 11:00 AM',
    deliveryAddress: 'Taj Hotel Central Kitchen, Colaba, Mumbai',
    logisticsPartner: 'Express Fresh Transit',
    logisticsTrackingId: 'TRK-9398-MH',
    estimatedDelivery: 'Delivered (Sept 02)',
  },
];

export const mockDisputeCases: DisputeCase[] = [
  {
    id: 'DSP-201',
    disputeNumber: '#DSP-104',
    orderId: 'ORD-9399',
    orderNumber: '#MK-9399',
    farmerName: 'Suresh Kumar',
    buyerName: 'AgroExport Co-Op',
    produceName: 'Oranges (Nagpur Grade 1)',
    cropName: 'Oranges (Nagpur Grade 1)',
    disputingParty: 'buyer',
    disputeReason: 'COLD_CHAIN_SPOILAGE',
    disputedAmount: 56000,
    amountDisputed: 56000,
    category: 'SPOILAGE',
    severity: 'CRITICAL',
    status: 'OPEN',
    openedAt: '2026-09-03 03:45 PM',
    farmerClaim: 'Produce was loaded in pristine condition at 18°C. Temperature spike occurred due to logistics reefer failure.',
    buyerClaim: 'Container arrived at JNPT with internal temp of 26°C. 35% of fruit showed mold and softening.',
    description: 'Buyer claims 35% of fruit arrived spoiled due to reefer truck refrigeration unit failure during transit.',
    evidencePhotoUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
    evidenceFiles: ['Reefer_Temp_Telemetry.pdf', 'Spoiled_Produce_Photo_1.jpg', 'Quality_Audit_JNPT.pdf'],
    weightSlipNumber: 'WS-NAG-49021',
    expectedGrade: 'Export Grade A',
    receivedGrade: 'Grade C (Softened/Spoiled)',
  },
  {
    id: 'DSP-202',
    disputeNumber: '#DSP-103',
    orderId: 'ORD-9385',
    orderNumber: '#MK-9385',
    farmerName: 'Baldev Singh',
    buyerName: 'Delhi Retail Marts',
    produceName: 'Cotton (Lokh Sabha Special)',
    cropName: 'Cotton (Lokh Sabha Special)',
    disputingParty: 'buyer',
    disputeReason: 'WEIGHT_DISCREPANCY_SHORTAGE',
    disputedAmount: 112000,
    amountDisputed: 112000,
    category: 'WEIGHT_MISMATCH',
    severity: 'CRITICAL',
    status: 'UNDER_REVIEW',
    openedAt: '2026-09-02 09:15 AM',
    farmerClaim: 'Weighbridge slip at Bathinda Mandi recorded exactly 4,000 kg gross weight before dispatch.',
    buyerClaim: 'Destination weighbridge at Azadpur recorded only 3,650 kg. Shortage of 350 kg (8.75%).',
    description: 'Shortage of 350 kg (8.75%) detected at destination weighbridge compared to dispatch manifest slip.',
    evidencePhotoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
    evidenceFiles: ['Bathinda_Weighbridge_Slip.pdf', 'Azadpur_Reciept_Weighbridge.pdf'],
    weightSlipNumber: 'WS-BAT-88201',
    expectedGrade: '4,000 kg Net Weight',
    receivedGrade: '3,650 kg Net Weight',
  },
  {
    id: 'DSP-203',
    disputeNumber: '#DSP-102',
    orderId: 'ORD-9372',
    orderNumber: '#MK-9372',
    farmerName: 'Manjula Rao',
    buyerName: 'Spices Export India',
    produceName: 'Red Chillies (Guntur Teja)',
    cropName: 'Red Chillies (Guntur Teja)',
    disputingParty: 'buyer',
    disputeReason: 'MOISTURE_SPEC_VIOLATION',
    disputedAmount: 42000,
    amountDisputed: 42000,
    category: 'QUALITY_GRADE_FAIL',
    severity: 'MAJOR',
    status: 'RESOLVED',
    openedAt: '2026-09-01 02:00 PM',
    farmerClaim: 'Moisture content was certified at 10.5% at Mandi assaying laboratory.',
    buyerClaim: 'Lab report upon receipt showed moisture at 13.8%, failing export specifications.',
    description: 'Moisture content failed export specs (13.8% vs 10.5% max target).',
    evidenceFiles: ['Guntur_Lab_Assay_Report.pdf'],
    expectedGrade: '10.5% Max Moisture',
    receivedGrade: '13.8% Moisture Detected',
    resolutionOutcome: '50/50 Partial Split Settlement Issued to both parties',
    arbitratorNote: 'Settled via 15% price concession. ₹35,700 released to farmer, ₹6,300 refunded to buyer.',
    resolutionSummary: 'Arbitration settled via 15% price concession. ₹35,700 released to farmer, ₹6,300 refunded to buyer.',
  },
];

export const MOCK_ORDERS = mockDetailedOrders;
export const MOCK_DISPUTES = mockDisputeCases;
