/**
 * MandiKart — Global Unified Environment Schema & Validator
 * Discovers and loads the single root .env file from the monorepo root
 * and enforces strict fail-fast validation for all secrets, APIs, and microservices.
 */
import { z } from 'zod';
export declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    PORT: z.ZodDefault<z.ZodNumber>;
    FARMER_BACKEND_PORT: z.ZodDefault<z.ZodNumber>;
    USER_BACKEND_PORT: z.ZodDefault<z.ZodNumber>;
    LOGISTIC_BACKEND_PORT: z.ZodDefault<z.ZodNumber>;
    ADMIN_BACKEND_PORT: z.ZodDefault<z.ZodNumber>;
    SUPABASE_URL: z.ZodDefault<z.ZodString>;
    SUPABASE_ANON_KEY: z.ZodDefault<z.ZodString>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodDefault<z.ZodString>;
    SUPABASE_STORAGE_BUCKET_AVATARS: z.ZodDefault<z.ZodString>;
    SUPABASE_STORAGE_BUCKET_PRODUCTS: z.ZodDefault<z.ZodString>;
    SUPABASE_STORAGE_BUCKET_LAND: z.ZodDefault<z.ZodString>;
    SUPABASE_STORAGE_BUCKET_POD: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    PII_ENCRYPTION_KEY: z.ZodDefault<z.ZodString>;
    SESSION_EXPIRY_HOURS: z.ZodDefault<z.ZodNumber>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_PUBLISHABLE_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
    STRIPE_CURRENCY: z.ZodDefault<z.ZodString>;
    FIREBASE_PROJECT_ID: z.ZodDefault<z.ZodString>;
    FIREBASE_API_KEY: z.ZodDefault<z.ZodString>;
    FIREBASE_AUTH_DOMAIN: z.ZodDefault<z.ZodString>;
    FIREBASE_DATABASE_URL: z.ZodDefault<z.ZodString>;
    FIREBASE_STORAGE_BUCKET: z.ZodDefault<z.ZodString>;
    FIREBASE_MESSAGING_SENDER_ID: z.ZodDefault<z.ZodString>;
    FIREBASE_APP_ID: z.ZodDefault<z.ZodString>;
    FIREBASE_MEASUREMENT_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    FIREBASE_SERVICE_ACCOUNT_PATH: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    OPEN_METEO_API_URL: z.ZodDefault<z.ZodString>;
    WEATHER_CACHE_TTL_MINUTES: z.ZodDefault<z.ZodNumber>;
    EXPO_PUBLIC_USER_API_URL: z.ZodDefault<z.ZodString>;
    EXPO_PUBLIC_FARMER_API_URL: z.ZodDefault<z.ZodString>;
    EXPO_PUBLIC_LOGISTIC_API_URL: z.ZodDefault<z.ZodString>;
    EXPO_PUBLIC_ADMIN_API_URL: z.ZodDefault<z.ZodString>;
    EXPO_PUBLIC_SUPABASE_URL: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_API_KEY: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_APP_ID: z.ZodOptional<z.ZodString>;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    CORS_ORIGIN: string;
    PORT: number;
    FARMER_BACKEND_PORT: number;
    USER_BACKEND_PORT: number;
    LOGISTIC_BACKEND_PORT: number;
    ADMIN_BACKEND_PORT: number;
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    SUPABASE_STORAGE_BUCKET_AVATARS: string;
    SUPABASE_STORAGE_BUCKET_PRODUCTS: string;
    SUPABASE_STORAGE_BUCKET_LAND: string;
    SUPABASE_STORAGE_BUCKET_POD: string;
    JWT_SECRET: string;
    PII_ENCRYPTION_KEY: string;
    SESSION_EXPIRY_HOURS: number;
    STRIPE_SECRET_KEY: string;
    STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    STRIPE_CURRENCY: string;
    FIREBASE_PROJECT_ID: string;
    FIREBASE_API_KEY: string;
    FIREBASE_AUTH_DOMAIN: string;
    FIREBASE_DATABASE_URL: string;
    FIREBASE_STORAGE_BUCKET: string;
    FIREBASE_MESSAGING_SENDER_ID: string;
    FIREBASE_APP_ID: string;
    FIREBASE_MEASUREMENT_ID: string;
    FIREBASE_SERVICE_ACCOUNT_PATH: string;
    OPEN_METEO_API_URL: string;
    WEATHER_CACHE_TTL_MINUTES: number;
    EXPO_PUBLIC_USER_API_URL: string;
    EXPO_PUBLIC_FARMER_API_URL: string;
    EXPO_PUBLIC_LOGISTIC_API_URL: string;
    EXPO_PUBLIC_ADMIN_API_URL: string;
    EXPO_PUBLIC_SUPABASE_URL?: string | undefined;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY?: string | undefined;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string | undefined;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string | undefined;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string | undefined;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID?: string | undefined;
}, {
    NODE_ENV?: "development" | "production" | "test" | undefined;
    CORS_ORIGIN?: string | undefined;
    PORT?: number | undefined;
    FARMER_BACKEND_PORT?: number | undefined;
    USER_BACKEND_PORT?: number | undefined;
    LOGISTIC_BACKEND_PORT?: number | undefined;
    ADMIN_BACKEND_PORT?: number | undefined;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    SUPABASE_STORAGE_BUCKET_AVATARS?: string | undefined;
    SUPABASE_STORAGE_BUCKET_PRODUCTS?: string | undefined;
    SUPABASE_STORAGE_BUCKET_LAND?: string | undefined;
    SUPABASE_STORAGE_BUCKET_POD?: string | undefined;
    JWT_SECRET?: string | undefined;
    PII_ENCRYPTION_KEY?: string | undefined;
    SESSION_EXPIRY_HOURS?: number | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_CURRENCY?: string | undefined;
    FIREBASE_PROJECT_ID?: string | undefined;
    FIREBASE_API_KEY?: string | undefined;
    FIREBASE_AUTH_DOMAIN?: string | undefined;
    FIREBASE_DATABASE_URL?: string | undefined;
    FIREBASE_STORAGE_BUCKET?: string | undefined;
    FIREBASE_MESSAGING_SENDER_ID?: string | undefined;
    FIREBASE_APP_ID?: string | undefined;
    FIREBASE_MEASUREMENT_ID?: string | undefined;
    FIREBASE_SERVICE_ACCOUNT_PATH?: string | undefined;
    OPEN_METEO_API_URL?: string | undefined;
    WEATHER_CACHE_TTL_MINUTES?: number | undefined;
    EXPO_PUBLIC_USER_API_URL?: string | undefined;
    EXPO_PUBLIC_FARMER_API_URL?: string | undefined;
    EXPO_PUBLIC_LOGISTIC_API_URL?: string | undefined;
    EXPO_PUBLIC_ADMIN_API_URL?: string | undefined;
    EXPO_PUBLIC_SUPABASE_URL?: string | undefined;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY?: string | undefined;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string | undefined;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string | undefined;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string | undefined;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string | undefined;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof EnvSchema>;
export declare function getValidatedEnv(): EnvConfig;
export declare function getLoadedEnvFilePath(): string | null;
